### ISSUE TITLE
miner stop mining when nodes are having same dataset.

### ISSUE THREAD

**Issue by totaloutput** [soteria-dag/soterd#1]
this is a corner case, but when the number of nodes in the network is small, it can happen (like now. :p )..
I can reproduce it locally, here are the steps:

1: have a sample set of data (in my case, I have 2000+ blocks in the db), copy it to data1 and data2.
2: start 2 soterd process with data1 and data2, for example: `--nodnsseed --datadir=/data1 -u USER -P PASS --rpclisten=0.0.0.0:5071 --listen=0.0.0.0:5070 --testnet --miningaddr=mrqvnRT17uBvozaaZXZJb2LSeWiWadx96N  ` and with `--datadir=/data2`
`--nodnsseed` option make sure it doesn't connect to the default seed node.
3: connect the 2 soterd process by `addnode`. then enable miner on one of them by `setgenerate true 1`
4: it stuck after `2019-04-30 00:03:55.751 [INF] MINR: CPU miner started`
this is because the sync manager still think we are in sync mode. here is the place that sync manager stop sync: https://github.com/soterium/soterd/blob/exp0/netsync/manager.go#L767
it's when sync manager handling a block.. However, because both nodes are at the same height (from same dataset), there won't be any blocks.. "no blocks" --> "no stop sync" --> "no mining" --> "no blocks"

**Comment by colakong** [comment]
Looked at preventing sync from starting during peer handshake, but we may not have enough information at that point to determine if we should do this.

Instead had the condition evaluated when processing `inv` messages.
