### ISSUE TITLE
new version check.

### ISSUE THREAD

**Issue by totaloutput** [soteria-dag/soterd#3]
I was hoping to use the soterd semantic versioning, because then we could say "Disconnect from the node if their MAJOR version is less than our MAJOR version" (in semver, MAJOR represents API-breaking changes: https://semver.org/)

But then we'd have to parse that info out of UserAgent field, and keep it in step with the soterd version info.

`UserAgent` field set when sending version messages
https://github.com/soterium/soterd/blob/exp0/wire/msgversion.go#L21

The _version_ of soterd:
https://github.com/soterium/soterd/blob/exp0/version.go#L19 (edited) 

So far, soterd is `0.12.0`, and the _UserAgent_ in p2p `version` messages is `0.5.0`
I feel like we should set both to `1.0.0` for testnet release, so that the version-check behaviour we want will work going forward, and we'll be able to detect incompatibilities from older soterd nodes from before our versioning check & change

**Comment by colakong** [comment]
Soterd now disconnects from nodes with different MAJOR versions than it. Version is now `1.0.0`, so nodes from this build onwards will disconnect from older soterd nodes (`0.12.0`)

To bump the version in the future, update the `version.go` file ^^
